require('config.lazy')
require('config.remap')
require('config.vim')
require('config.colorscheme')

require('config.lsp')
require('config.telescope')
require('config.whichkey')
require('config.comment')
require('config.treesitter')
require('config.zenmode')
