
# you can set default environment variables with
# [env]
# VARIABLE=1

[window]
dynamic_padding = true
padding = { x = 6, y = 6 }
decorations = "Full"
opacity = 1 # 0.95

dynamic_title = true
resize_increments = true

[scrolling]
history = 100000
multiplier = 5

[font]
size = 9
normal = { family = "Adwaita Mono Nerd Font", style = "Regular"}
# bold = { family = "Adwaita Mono Nerd Font", style = "Bold"}
italic = { family = "monospace", style = "Italic"}
builtin_box_drawing = false

[bell]
duration = 0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On"}
vi_mode_style = { shape = "Block", blinking = "On"}
thickness = 0.15

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
	{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]

[general]
# you can import other files like this
# import = ["",""]

live_config_reload = true
