[general]
live_config_reload = true

[window]
dynamic_padding = true
padding = { x = 6, y = 6 }
decorations = "Full"
opacity = 0.95
decorations_theme_variant="Dark"
dynamic_title = true
resize_increments = true

[scrolling]
history = 100000
multiplier = 5

[font]
size = 9
normal = { family = "JetBrainsMono NF", style = "Regular"}
# builtin_box_drawing = false # default is true

[bell]
duration = 0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On"}
vi_mode_style = { shape = "Block", blinking = "On"}
thickness = 0.15

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
	{ key = "F11", mods = "None", action = "ToggleFullscreen" },
	{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
	# { key = "U", mods = "Control|Shift", action = "ClearHistory" },
	# { key = "I", mods = "Control", action = "ScrollHalfPageUp" },
	# { key = "O", mods = "Control", action = "ScrollHalfPageDown" },
]

# [colors.primary]
# background = "#1d1f21"
# foreground = "#c5c8c6"
#
# [colors.normal]
# black = "#1d1f21"
# red = "#cc6666"
# green = "#b5bd68"
# yellow = "#f0c674"
# blue = "#81a2be"
# magenta = "#b294bb"
# cyan = "#8abeb7"
# white = "#c5c8c6"
