[general]
# you can import other files like this
# import = ["",""]

# working_directory = "$HOME"

# you can set default environment variables with
# [env]
# VARIABLE=1

[window]
dynamic_padding = true
padding = { x = 6, y = 6 }
decorations = "Full"
opacity = 1.0

dynamic_title = true
resize_increments = true

[scrolling]
history = 100000
multiplier = 5
# markaplier???

[font]
size = 12
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
# bold = { family = "JetBrainsMono Nerd Font", style = "Bold"}
# italic = { family = "JetBrainsMono Nerd Font", style = "Italic"}
builtin_box_drawing = false

[bell]
duration = 0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On"}
vi_mode_style = { shape = "Block", blinking = "On"}
thickness = 0.15

[mouse]
hide_when_typing = false
