# .bash_aliases

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    # alias ls='ls --color=auto'
	alias lsc="ls -ltskhtr --color --group-directories-first"
	alias ll='ls -alF'
	alias la='ls -A'
	alias l='ls -CF'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Aliases
alias aliases="cat $HOME/.bashrc | grep alias"
alias dnfi="sudo dnf install -y"
alias dnfr="sudo dnf remove -y"
# Fetch
alias ff='clear; pyfiglet -s $(hostname) && fastfetch -l none'
# Git
alias ga="git add"
alias gs="git status"
alias gp="git push"
alias gc="git checkout"
alias gsw="git switch"
alias gd="git diff"
alias gr="git restore"
alias grs="git restore --staged"
alias gcm="git commit -m"
