# .bashrc

# Defaul bash
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific binaries path
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Environment
export HISTSIZE=10000
export EDITOR=nvim

# Number of trailing dirs on prompt
export PROMPT_DIRTRIM=2

# PS1='[\u@\h] \w $ '

# Common
alias aliases="cat $HOME/.bashrc | grep alias"
alias lsc="ls -xogskhtr --color"
alias dnfi="sudo dnf install -y"
alias dnfr="sudo dnf remove -y"

# Fetch
alias ff="fastfetch"

# Git
alias ga="git add"
alias gs="git status"
alias gp="git push"
alias gc="git checkout"
alias gsw="git switch"
alias gd="git diff"
alias gr="git restore"
alias grs="git restore --staged"
alias gcm="git commit -m"

# File manager
if which nnn >/dev/null 2>&1 ;then								# check if tmux is installed
	source $HOME/.dotfiles/config/nnn.config
fi

# Tmux
if which tmux >/dev/null 2>&1 ;then								# check if tmux is installed
	if [[ -z "$TMUX" ]] ;then									# do not allow "tmux in tmux"
		ID="$( tmux ls | grep -vm1 attached | cut -d: -f1 )"    # get the id of a deattached session
		if [[ -z "$ID" ]] ;then                                 # if not available
			tmux new-session									# start new session
		else													# if available
			tmux attach-session -t "$ID"						# attach to it
		fi
	fi
fi

# Fastfetch
if [[ $- != *i* ]] ;then						# is interactive
    return;										# don´t run it
else
	if which fastfetch >/dev/null 2>&1 ;then	# check if installed
		fastfetch								# run fastfetch
    fi
fi

# Remove X11-specific variables
unset XDG_SESSION_TYPE XDG_CURRENT_DESKTOP

# Set Wayland variables
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
export MOZ_ENABLE_WAYLAND=1  # Enable Wayland for Firefox
export QT_QPA_PLATFORM=wayland  # Qt apps
export SDL_VIDEODRIVER=wayland  # SDL games
export GDK_SCALE=2  # For GTK apps
export QT_SCALE_FACTOR=2  # For Qt apps
